---
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.1.0

    steps:
      - checkout

      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}

      - run:
        name: dependency
        command: npm install

      - run:
        name: test
        command: npm test

      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules

      - run:
        name: coverage
        command: npm run coverage

      - store_artifacts:
        path: coverage
        prefix: coverage
